"""Position book for operational backtests."""

from __future__ import annotations

from collections.abc import Iterable, Mapping
from dataclasses import dataclass, field
from typing import Any


@dataclass
class PositionRecord:
    instrument: str
    quantity: float = 0.0
    avg_entry: float = 0.0
    price: float = 0.0
    realized_pnl: float = 0.0
    unrealized_pnl: float = 0.0
    currency: str = "USD"
    exposure: float = 0.0

    @property
    def market_value(self) -> float:
        return float(self.quantity) * float(self.price)

    def mark(self, price: float) -> None:
        self.price = float(price)
        self.unrealized_pnl = (float(self.price) - float(self.avg_entry)) * float(self.quantity)
        self.exposure = abs(self.market_value)

    def to_dict(self) -> dict[str, Any]:
        return {
            "instrument": self.instrument,
            "quantity": float(self.quantity),
            "avg_entry": float(self.avg_entry),
            "price": float(self.price),
            "market_value": float(self.market_value),
            "realized_pnl": float(self.realized_pnl),
            "unrealized_pnl": float(self.unrealized_pnl),
            "currency": self.currency,
            "exposure": float(self.exposure),
        }

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> PositionRecord:
        return cls(
            instrument=str(data["instrument"]),
            quantity=float(data.get("quantity", 0.0)),
            avg_entry=float(data.get("avg_entry", 0.0)),
            price=float(data.get("price", 0.0)),
            realized_pnl=float(data.get("realized_pnl", 0.0)),
            unrealized_pnl=float(data.get("unrealized_pnl", 0.0)),
            currency=str(data.get("currency", "USD")),
            exposure=float(data.get("exposure", 0.0)),
        )


@dataclass
class PositionBook:
    positions: dict[str, PositionRecord] = field(default_factory=dict)
    currency: str = "USD"

    def get(self, instrument: str) -> PositionRecord:
        inst = str(instrument)
        if inst not in self.positions:
            self.positions[inst] = PositionRecord(instrument=inst, currency=self.currency)
        return self.positions[inst]

    def quantities(self) -> dict[str, float]:
        return {k: float(v.quantity) for k, v in self.positions.items() if abs(v.quantity) > 1e-12}

    def market_values(self) -> dict[str, float]:
        return {k: float(v.market_value) for k, v in self.positions.items()}

    def total_market_value(self) -> float:
        return float(sum(v.market_value for v in self.positions.values()))

    def total_unrealized(self) -> float:
        return float(sum(v.unrealized_pnl for v in self.positions.values()))

    def total_realized(self) -> float:
        return float(sum(v.realized_pnl for v in self.positions.values()))

    def total_exposure(self) -> float:
        return float(sum(abs(v.market_value) for v in self.positions.values()))

    def mark_all(self, prices: Mapping[str, float]) -> None:
        for inst, px in prices.items():
            if inst in self.positions and abs(self.positions[inst].quantity) > 1e-12:
                self.positions[inst].mark(float(px))

    def apply_fill(
        self,
        instrument: str,
        *,
        quantity: float,
        price: float,
        side: str = "buy",
    ) -> float:
        """Apply a fill; return realized PnL generated by this fill."""
        pos = self.get(instrument)
        qty = abs(float(quantity))
        px = float(price)
        side_l = str(side).strip().lower()
        signed = qty if side_l in {"buy", "b", "cover", "long"} else -qty
        realized = 0.0

        if abs(pos.quantity) < 1e-15 or pos.quantity * signed >= 0:
            # Opening / adding
            new_qty = pos.quantity + signed
            if abs(new_qty) < 1e-12:
                pos.quantity = 0.0
                pos.avg_entry = 0.0
            else:
                if abs(pos.quantity) < 1e-15:
                    pos.avg_entry = px
                else:
                    pos.avg_entry = (
                        abs(pos.quantity) * float(pos.avg_entry) + abs(signed) * px
                    ) / (abs(pos.quantity) + abs(signed))
                pos.quantity = new_qty
        else:
            # Reducing / flipping
            close_qty = min(abs(pos.quantity), abs(signed))
            direction = 1.0 if pos.quantity > 0 else -1.0
            realized = (px - float(pos.avg_entry)) * close_qty * direction
            pos.realized_pnl += realized
            remaining = pos.quantity + signed
            if abs(remaining) < 1e-12:
                pos.quantity = 0.0
                pos.avg_entry = 0.0
            elif pos.quantity * remaining < 0:
                # Flip
                pos.quantity = remaining
                pos.avg_entry = px
            else:
                pos.quantity = remaining

        pos.mark(px)
        return float(realized)

    def open_instruments(self) -> list[str]:
        return sorted(k for k, v in self.positions.items() if abs(v.quantity) > 1e-12)

    def snapshot(self) -> list[dict[str, Any]]:
        return [v.to_dict() for v in self.positions.values() if abs(v.quantity) > 1e-12]

    def to_dict(self) -> dict[str, Any]:
        return {
            "currency": self.currency,
            "positions": {k: v.to_dict() for k, v in self.positions.items()},
        }

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> PositionBook:
        book = cls(currency=str(data.get("currency", "USD")))
        for k, v in dict(data.get("positions") or {}).items():
            book.positions[str(k)] = PositionRecord.from_dict(v)
        return book

    def iter_open(self) -> Iterable[PositionRecord]:
        for p in self.positions.values():
            if abs(p.quantity) > 1e-12:
                yield p


__all__ = ["PositionBook", "PositionRecord"]
